name: xcord
description: A professional multi-language Discord app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  url_launcher: ^6.1.10
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_database: ^10.2.5
  firebase_analytics: ^10.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - images/spam.png
    - images/nuke.png
    - images/copyer.png
    - images/boost-tool.png
    - images/logo.png
    - images/xxicon.png
    - images/checker.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/xxicon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "images/xxicon.png"
  remove_alpha_ios: true